### ISSUE TITLE
Serious Bug: How to handle disconnects?

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/tracey-jenkins-trigger-plugin#10]
Currently, when we save the job, a trigger is created, that is a connection is established to rabbitmq. 

What happens now, is that when the connection is severed, server side (RabbitMQ server) we are not able to re-establish connection UNTIL the job is saved again. 

I think we need to handle this in the consumer, to build in an attempt to re-establish connection. 

Require investigation.

**Comment by Andrey9kin** [comment]
@MadsNielsen a good catch! We should make sure to write such event to the log so user have possibility to debug triggering issues

**Comment by Andrey9kin** [comment]
@MadsNielsen BTW, how about implementing watchdogs similar to one used in Gerrit Trigger plugin? Just check connection every second and reestablish it if broken

**Comment by MadsNielsen** [comment]
@Andrey9kin That is a possible solution, i will need to take a look at the mechanics, on how to just re-establish the connection to rabbitmq. Currently we create the Channel, and the queues when the job is saved and start listening.

**Comment by MadsNielsen** [comment]
This was so much simpler than i thought... 
https://www.rabbitmq.com/api-guide.html
It's fixed in Tracey broker :+1:
