### ISSUE TITLE
Job that contains tracey trigger and generated using JobDSL can't be saved

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-jenkins-trigger-plugin#22]
I'm using the following DSL

job("tracey-demo-scm-trigger") {
        triggers {
            tracey('tracey', 'demo')
    }
    steps {
        shell('env')
    }
}

Job generates just fine but it is possible to save, i.e. enter configuration screen for the generated job and try to press save. Manually created jobs works fine

jmaster_1  | WARNING: Error while serving http://192.168.99.100:8080/job/tracey-demo-scm-trigger/configSubmit
jmaster_1  | java.lang.reflect.InvocationTargetException
jmaster_1  |   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jmaster_1  |   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jmaster_1  |   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jmaster_1  |   	at java.lang.reflect.Method.invoke(Method.java:498)
jmaster_1  |   	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
jmaster_1  |   	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
jmaster_1  |   	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
jmaster_1  |   	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
jmaster_1  |   	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
jmaster_1  |   	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
jmaster_1  |   	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
jmaster_1  |   	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
jmaster_1  |   	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
jmaster_1  |   	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
jmaster_1  |   	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
jmaster_1  |   	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
jmaster_1  |   	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
jmaster_1  |   	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
jmaster_1  |   	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jmaster_1  |   	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
jmaster_1  |   	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
jmaster_1  |   	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
jmaster_1  |   	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
jmaster_1  |   	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
jmaster_1  |   	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
jmaster_1  |   	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
jmaster_1  |   	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
jmaster_1  |   	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
jmaster_1  |   	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
jmaster_1  |   	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
jmaster_1  |   	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
jmaster_1  |   	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
jmaster_1  |   	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
jmaster_1  |   	at org.eclipse.jetty.server.Server.handle(Server.java:370)
jmaster_1  |   	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
jmaster_1  |   	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
jmaster_1  |   	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
jmaster_1  |   	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
jmaster_1  |   	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
jmaster_1  |   	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
jmaster_1  |   	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
jmaster_1  |   	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
jmaster_1  |   	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
jmaster_1  |   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jmaster_1  |   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jmaster_1  |   	at java.lang.Thread.run(Thread.java:745)
jmaster_1  | Caused by: java.lang.NullPointerException
jmaster_1  |   	at org.jenkinsci.tracey.TraceyTrigger.stop(TraceyTrigger.java:132)
jmaster_1  |   	at hudson.model.AbstractProject.submit(AbstractProject.java:1867)
jmaster_1  |   	at hudson.model.Project.submit(Project.java:230)
jmaster_1  |   	at hudson.model.Job.doConfigSubmit(Job.java:1225)
jmaster_1  |   	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:795)
jmaster_1  |   	... 73 more

**Comment by MadsNielsen** [comment]
I know what the issue is...it's a fuckup on my part. 

I made an error when you select the tracey host. It uses 'credential-id' to select the correct host configuration and not the description. 

tracey('tracey', 'demo' ) 
}

In the case above 'demo' should be the credentialid that is tied to the selected host configuration...I need to introuduce a host-uuid in order to uniquely select the host, and not use the credentials id.
