### ISSUE TITLE
Add unit tests for new filters format 

### ISSUE THREAD

**Issue by alexsedova** [Praqma/tracey-jenkins-trigger-plugin#40]

**Comment by Andrey9kin** [comment]
@alexsedova shall we close this one since those test should be done in praqma/tracey-broker?

**Comment by alexsedova** [comment]
@Andrey9kin Yes please

**Comment by Andrey9kin** [comment]
@alexsedova you should have an access to close issues by yourself. Next time do not hesitate to do a clean up
